### ISSUE TITLE
Switch from `structopt` to `clap` v3

### ISSUE THREAD

**Issue by d-e-s-o** [d-e-s-o/apcacli#3]
We should convert the crate from using [structopt](https://docs.rs/structopt/0.3.26/structopt/index.html) to using [clap](https://docs.rs/clap/3.1.17/clap/) v3, which is the new kid on the block for argument parsing (well, sort of, v2 has been around for ages and was the de-facto standard, but v3 does a few more things). I recall there being some kind of tutorial specifically aimed at conversions like this, though I couldn't find it off hand. May be useful to check for that first. My notes reference [this](https://github.com/clap-rs/clap/blob/3d8ce3f4268e4fd02549a9cea32f18965272ac50/CHANGELOG.md#breaking-changes), but I was under the impression there was a more formal document.

**Comment by husafan** [comment]
https://www.youtube.com/watch?v=I2RBAT5Tu2I
